{% set name = "PyMUMPS" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
  
source:
  fn: {{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1b55cdc7c3998fda874d8078d2348228a6759cc5bed00f3f1fc1745ce727e43d

build:
  number: 0
  script: |
    pip install -v -C build.verbose=true -C cmake.define.MUMPS_ROOT=$PREFIX .           # [osx or linux]
    pip install -v -C build.verbose=true -C cmake.define.MUMPS_ROOT=%PREFIX%\Library .  # [win]
  
requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - cython
    - python
    - mumps-seq      # [win]
    - mumps-mpi      # [osx or linux]
    - mumps-include  # [osx or linux]
    - cmake
    - mpi4py
    - pip
  run:
    - python
    - numpy
    - mumps-seq      # [win]
    - mumps-mpi      # [osx or linux]
    - mpi4py

test:
  source_files:
    - tests
  imports:
    - mumps
  requires:
    - cython
    - mumps-seq      # [win]
    - mumps-mpi      # [osx or linux]
    - mumps-include  # [osx or linux]
    - python
    - mpi4py
    - numpy
    - scipy
    - pytest
  commands:
    - pytest


about:
  home: https://github.com/PyMUMPS/pymumps.git
  license: BSD-3-Clause
  license_file: COPYING
  summary: 'PyMUMPS: Python parallel sparse direct solver'

extra:
  recipe-maintainers:
    - santiagoropb
    - sdrave
